- shell:
    - [curl -L git.io/antigen > zsh/antigen.zsh, Installing Antigen]

- link:
    ~/.antigen.zsh: zsh/antigen.zsh
    ~/.zshenv: zsh/zshenv
    ~/.zshrc: zsh/zshrc
    ~/.zsh_aliases: zsh/zsh_aliases

