export LANG=en_US.UTF-8
export LESSCHARSET='utf-8'
export EDITOR='vim'
export SUDO_EDITOR='vim'
export SSH_KEY_PATH="~/.ssh/id_rsa"
# export ARCHFLAGS="-arch x86_64"
# export MANPATH="/usr/local/man:$MANPATH"

