export DEFAULT_USER=teo
export LANG=en_US.UTF-8
export LESSCHARSET='utf-8'
export EDITOR='vim'
export SUDO_EDITOR='vim'
export SSH_KEY_PATH="~/.ssh/id_rsa"
# export ARCHFLAGS="-arch x86_64"
# export MANPATH="/usr/local/man:$MANPATH"

# Gurobi
if [ -d "/opt/gurobi651" ]; then
    export GUROBI_HOME="/opt/gurobi651/linux64"
    export PATH="${PATH}:${GUROBI_HOME}/bin"
    export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${GUROBI_HOME}/lib"
fi

